- name: "Install network debugging tools"
  apt: name={{ item }} state=latest
  with_items:
    - apache2-utils
    - bash-completion
    - bc
    - bind9-host
    - bison
    - build-essential
    - bzr
    - command-not-found
    - curl
    - cvs
    - dbndns
    - dnsutils
    - dsniff
    - flex
    - fpdns
    - fping
    - git-core
    - gnupg
    - gnutls-bin
    - graphviz
    - htop
    - httping
    - iotop
    - ipcalc
    - iperf
    - iputils-ping
    - iputils-tracepath
    - jq
    - landscape-common
    - language-pack-en-base
    - ldnsutils
    - lftp
    - libcache-cache-perl
    - libnet-ssh2-ruby1.8
    - libxml2-dev
    - lsof
    - ltrace
    - lynx
    - man-db
    - markdown
    - mercurial
    - moreutils
    - mtr-tiny
    - ndisc6
    - netcat-openbsd
    - netsed
    - ngrep
    - pastebinit
    - php5-cli
    - psmisc
    - pv
    - python
    - python-beautifulsoup
    - python-demjson
    - python-dnspython
    - python-flask
    - python-ipaddr
    - python-libxml2
    - python-mysqldb
    - python-networkx
    - python-pip
    - python-pycountry
    - python-setuptools
    - python-simplejson
    - python-software-properties
    - python-virtualenv
    - ringfpingd
    - rsync
    - ruby1.9.1-dev
    - screen
    - sipcalc
    - snmp
    - socat
    - sshfp
    - strace
    - sysstat
    - tcptraceroute
    - telnet
    - tmux
    - ucspi-tcp
    - unattended-upgrades
    - update-manager-core
    - update-notifier-common
    - vim
    - virt-what
    - w3m
    - wget
    - whois
    - swaks
    - ruby-json

- name: "Uninstall certain unnecessary packages"
  apt: name={{ item }} state=absent
  with_items:
    - pppoe
    - ppp
    - pppconfig
    - pppoeconfig
    - resolvconf
    - ferm
    - ufw
    - apparmor
    - apparmor-utils
    - molly-guard
