- name: "Install prequisites for apt_repository"
  apt: name={{ item }} state=latest
  with_items:
    - python-apt
    - ca-certificates

- name: "Clean sources.list"
  copy:
    src=sources.list
    dest=/etc/apt/sources.list
    owner=root
    group=root
    mode=0644

- name: "Remove old repo files"
  file: name={{ item }} state=absent
  with_items:
    - '/etc/apt/sources.list.d/ubuntu_archiv_precise.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_precise-updates.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_precise-security.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-updates.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-security.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-updates.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-security.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-security.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-updates.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-security.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-updates.list.distUpgrade'

- name: "Add ubuntu {{ ansible_distribution_release }} repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}'

- name: "Add ubuntu {{ ansible_distribution_release }} updates repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }}-updates main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}-updates'

- name: "Add ubuntu {{ ansible_distribution_release }} security repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}-security'

- name: "Install nlnog repo key"
  apt_key:
    id: 37B0CA14
    url: "https://ring.nlnog.net/nlnogrepopublic.key"
    state: present

- name: "Remove old nlnog apt repository"
  apt_repository:
    repo: 'deb http://apt.ring.nlnog.net/deb/ maverick main'
    state: absent
    filename: 'nlnog_ring_repo'

- name: "Add nlnog apt repository"
  apt_repository:
    repo: 'deb http://apt.ring.nlnog.net/deb/ ring main'
    state: present
    filename: 'nlnog_ring_repo'

- name: "Install ansible repo key"
  apt_key:
    id: 7BB9C367
    url: "https://ring.nlnog.net/ansiblerepopublic.key"
    state: present
  when: ansible_distribution_release == "precise"

- name: "Remove ansible repo key"
  apt_key:
    id: 7BB9C367
    url: "https://ring.nlnog.net/ansiblerepopublic.key"
    state: absent
  when: ansible_distribution_release != "precise"

- name: "Add ansible repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu precise main'
    state: present
    filename: 'ansible_repo'
  when: ansible_distribution_release == "precise"

- name: "Remove ansible repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu precise main'
    state: absent
    filename: 'ansible_repo'
  when: ansible_distribution_release != "precise"

- name: "Add apt configuration files"
  copy:
    src={{ item }}
    dest=/etc/apt/apt.conf.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: "Create /etc/systemd/system/apt-daily-upgrade.timer.d if needed"
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
    mode: 0755

- name: "Randomise apt upgrade and reboot activities across 23 hours"
  copy:
    src=apt-daily-upgrade.timer
    dest=/etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    owner=root
    group=root
    mode=0644
  notify: reload systemd


- name: "Reset system default splay back to 1h"
  lineinfile: dest=/lib/systemd/system/apt-daily-upgrade.timer regexp='^RandomizedDelaySec=' line='RandomizedDelaySec=1h'
  notify: reload systemd
  when: ansible_distribution_release != "precise"


- name: reload systemd if needed
  meta: flush_handlers
  when: ansible_distribution_release != "precise"

- name: "Run apt-get update"
  apt:
    update_cache: yes
  changed_when: false
