- name: "Remove old repo files"
  file: name={{ item }} state=absent
  with_items:
    - '/etc/apt/sources.list.d/ubuntu_archiv_precise.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_precise-updates.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_precise-security.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-updates.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-security.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-updates.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-security.list'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-security.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_trusty-updates.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-security.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_xenial-updates.list.distUpgrade'
    - '/etc/apt/sources.list.d/bit_debian_bookworm.list'
    - '/etc/apt/sources.list.d/bit_ubuntu_archiv_hirsute.list'
    - '/etc/apt/sources.list.d/bit_ubuntu_archiv_xenial.list'
    - '/etc/apt/sources.list.d/bit_ubuntu_archiv_xenial-security.list'
    - '/etc/apt/sources.list.d/bit_ubuntu_archiv_xenial-updates.list'
    - '/etc/apt/sources.list.d/bit_ubuntu_archiv_xenial.list.distUpgrade'
    - '/etc/apt/sources.list.d/bit_ubuntu_archiv_xenial-security.list.distUpgrade'
    - '/etc/apt/sources.list.d/bit_ubuntu_archiv_xenial-updates.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_bionic.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_bionic-security.list.distUpgrade'
    - '/etc/apt/sources.list.d/ubuntu_archiv_bionic-updates.list.distUpgrade'
    - '/etc/apt/sources.list.d/nlnog_ring_repo.list.distUpgrade'
    - '/etc/apt/sources.list.distUpgrade'

- name: "Install prerequisites for apt_repository"
  apt: name={{ item }} state=latest
  with_items:
    - python-apt
    - ca-certificates
  when: ansible_distribution_release == "bionic"

- name: "Install prerequisites for apt_repository"
  apt: name={{ item }} state=latest
  with_items:
    - python3-apt
    - ca-certificates
  when: ansible_distribution_release == "jammy"

- name: "Clean sources.list"
  copy:
    src=sources.list
    dest=/etc/apt/sources.list
    owner=root
    group=root
    mode=0644

- name: "Add ubuntu {{ ansible_distribution_release }} repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }} main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}'

- name: "Add ubuntu {{ ansible_distribution_release }} updates repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }}-updates main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}-updates'

- name: "Add ubuntu {{ ansible_distribution_release }} security repository"
  apt_repository:
    repo: 'deb http://ftp.bit.nl/ubuntu {{ ansible_distribution_release }}-security main restricted universe multiverse'
    state: present
    filename: 'bit_ubuntu_archiv_{{ ansible_distribution_release }}-security'

- name: "Install nlnog repo key"
  apt_key:
    id: B1BA5ACA
    url: "https://ring.nlnog.net/nlnogrepopublic.key"
    state: present

- name: "Remove Debian Bullseye/11 APT key"
  apt_key:
    id: 1F89983E0081FDE018F3CC9673A4F27B8DD47936
    state: absent

- name: "Remove Debian Buster/10 APT key"
  apt_key:
    id: 80D15823B7FD1561F9F7BCDDDC30D7C23CBBABEE
    state: absent

- name: "Remove old nlnog apt repository"
  apt_repository:
    repo: 'deb http://apt.ring.nlnog.net/deb/ maverick main'
    state: absent
    filename: 'nlnog_ring_repo'

- name: "Add nlnog apt repository"
  apt_repository:
    repo: 'deb [arch=amd64] http://apt.ring.nlnog.net/deb/ ring main'
    state: present
    filename: 'nlnog_ring_repo'

- name: "Install unattended-upgrades"
  apt: name=unattended-upgrades state=latest

- name: "Install byobu (provides purge-old-kernels)"
  apt: name=byobu state=latest

- name: "Add apt configuration files"
  copy:
    src={{ item }}
    dest=/etc/apt/apt.conf.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
  notify: restart unattended-upgrades

- name: "Create /etc/systemd/system/apt-daily-upgrade.timer.d if needed"
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
    mode: 0755

- name: "Randomise apt upgrade and reboot activities across 23 hours"
  copy:
    src=apt-daily-upgrade.timer
    dest=/etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    owner=root
    group=root
    mode=0644
  notify: reload systemd

- name: "Check for apt-daily-upgrade.timer"
  stat: path=/lib/systemd/system/apt-daily-upgrade.timer
  register: apt_daily_upgrade_timer

- name: "Reset system default splay back to 1h"
  lineinfile: dest=/lib/systemd/system/apt-daily-upgrade.timer regexp='^RandomizedDelaySec=' line='RandomizedDelaySec=1h'
  notify: reload systemd
  when: apt_daily_upgrade_timer.stat.exists == True

- name: reload systemd if needed
  meta: flush_handlers

- name: "Purge old kernels"
  command: /usr/bin/purge-old-kernels -y

- name: "Run apt-get update"
  apt:
    update_cache: yes
  changed_when: false

- name: "Fix half-configured packages"
  command: dpkg --configure -a
  changed_when: false
