- name: "Add ubuntu precise repository"
  apt_repository:
    repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt precise main restricted universe multiverse'
    state: present
    filename: 'ubuntu_archiv_precise'

- name: "Add ubuntu precise updates repository"
  apt_repository:
    repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt precise-updates main restricted universe multiverse'
    state: present
    filename: 'ubuntu_archiv_precise-updates'

- name: "Add ubuntu precise security repository"
  apt_repository:
    repo: 'deb mirror://mirrors.ubuntu.com/mirrors.txt precise-security main restricted universe multiverse'
    state: present
    filename: 'ubuntu_archiv_precise-security'

- name: "Install nlnog repo key"
  apt_key:
    id: 37B0CA14
    url: "https://ring.nlnog.net/nlnogrepopublic.key"
    state: present

- name: "Add nlnog apt repository"
  apt_repository:
    repo: 'deb http://apt.ring.nlnog.net/deb/ maverick main'
    state: present
    filename: 'nlnog_ring_repo'

- name: "Install ansible repo key"
  apt_key:
    id: 7BB9C367
    url: "https://ring.nlnog.net/ansiblerepopublic.key"
    state: present

- name: "Add ansible repository"
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu precise main'
    state: present
    filename: 'ansible_repo'

- name: "Add apt configuration files"
  copy:
    src={{ item }}
    dest=/etc/apt/apt.conf.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
