- name: "Ensure the hostname is set in /etc/hostname"
  copy:
    dest: /etc/hostname
    content: "{{ ansible_nodename }}"

- name: "Ensure the hostname is set"
  hostname:
    name: "{{ ansible_nodename }}"

- name: "Add /etc/rc.local"
  template:
    src: rc.local.j2
    dest: /etc/rc.local

- name: "Generate /etc/hosts"
  template: src=hosts.j2 dest=/etc/hosts

- name: "Update /etc/ssh/ssh_known_hosts"
  copy:
    src=ssh_known_hosts
    dest=/etc/ssh/ssh_known_hosts
    owner=root
    group=root
    mode=0644

- name: "Add upstart-job"
  copy:
    src=upstart-job
    dest=/lib/init/upstart-job
    owner=root
    group=root
    mode=0755

- name: "Disable multiarch"
  file:
    path: /etc/dpkg/dpkg.cfg.d/multiarch
    state: absent

- name: "Update /etc/bash.bashrc"
  copy:
    src=bash.bashrc
    dest=/etc/bash.bashrc
    owner=root
    group=root
    mode=0644

- name: "Update pam configuration"
  copy:
    src=pam_{{ item }}
    dest=/etc/pam.d/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
    - atd
    - cron
    - login
    - sshd
    - su

- name: "Set localtime"
  file:
    src: /usr/share/zoneinfo/UTC
    dest: /etc/localtime
    state: link

- name: "Update timezone file"
  copy:
    src=timezone
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644

