---
lg_peers:
  A2B1:
    asn: 51088
    ipv4: 5.10.192.4
    ipv6: 2a02:1668:a2b:1:3::1
  ACCURIS1:
    asn: 52210
    ipv4: 23.130.139.83
    ipv6: 2602:fcd3:1:1::13
  AFILIAS_AMS2:
    asn: 198260
    ipv4: 199.10.66.251
    ipv6: 2001:500:f1::251
  AFILIAS_IAD1:
    asn: 393246
    ipv4: 199.115.158.251
    ipv6: 2001:500:a6::251
  AFILIAS_LAX1:
    asn: 63403
    ipv4: 199.19.51.251
    ipv6: 2a01:8840:d::251
  AFILIAS_MIA2:
    asn: 33280
    ipv4: 65.22.12.251
    ipv6: 2a01:8840:c::251
  AFILIAS_NRT1:
    asn: 13901
    ipv4: 199.19.52.251
    ipv6: 2001:500:a::251
  ALARIG1:
    asn: 208627
    ipv4: 45.91.126.248
    ipv6: '2a0e:f42:ffff::'
  ALARIG2:
    asn: 208627
    ipv4: 45.91.126.255
    ipv6: 2a0e:f42:ffff::1
  ALTIBOX1:
    asn: 29695
    ipv4: 79.160.115.253
    ipv6: 2a01:798:0:1::262
  AMIRGT_FSN:
    asn: 207740
    ipv6: 2a0e:b107:198::1
  ANDREWNET1:
    asn: 1003
    ipv4: 192.189.65.162
    ipv6: 2602:fc26:12::1
  APERNET_HKG:
    asn: 38008
    ipv4: 103.152.35.254
    ipv6: 2406:4440::1
  APGP01:
    asn: 54316
    ipv4: 23.175.208.254
    ipv6: 2602:fcad:1:ffff::ffff
  AQUILENET1:
    asn: 198985
    ipv4: 185.233.100.246
    ipv6: 2a0c:e300:1::246
  AQUILENET2:
    asn: 198985
    ipv4: 185.233.100.247
    ipv6: 2a0c:e300:1::247
  AS199471_S5B_DUS:
    asn: 199471
    ipv4: 185.83.87.2
    ipv6: 2a13:fc80:fffe::1
  AS199471_S5B_FRA:
    asn: 199471
    ipv4: 185.83.87.0
    ipv6: 2a13:fc80:fffd::1
  AS203686_ILHAM_RR:
    asn: 203686
    ipv6: 2a05:dfc1:7e00:abcd::5
  AS207960NET1:
    asn: 207960
    ipv4: 45.129.95.2
    ipv6: 2a0d:1a40:7900:7::1
  AS212635_AMS2:
    asn: 212635
    ipv4: 45.159.140.2
    ipv6: 2a10:6e40::2
  ATHARVA:
    asn: 150249
    ipv4: 103.153.42.74
    ipv6: 2a06:9f44:f170:ff::2
  ATOM861:
    asn: 8455
    ipv4: 95.142.96.25
    ipv6: 2a00:1188::10
  ATOM862:
    asn: 8455
    ipv4: 95.142.96.26
    ipv6: 2a00:1188::11
  ATOM863:
    asn: 8455
    ipv4: 95.142.96.73
    ipv6: 2a00:1188:2::100
  ATT1:
    asn: 7018
    ipv4: 12.0.1.63
    ipv6: 2001:1890:111d:1::63
  AUGUST:
    asn: 945
    ipv4: 23.150.8.14
    ipv6: 2602:234:1::8
  BAKKERIT01:
    asn: 44103
    ipv4: 185.235.144.33
    ipv6: '2a11:2:10::'
  BELWUE1:
    asn: 553
    ipv4: 129.143.4.66
    ipv6: 2001:7c0::179:1
  BIT1:
    asn: 12859
    ipv4: 213.136.1.132
    ipv6: 2001:7b8:0:fffe::2
  BITENCY_EQAM5:
    asn: 61029
    ipv4: 37.72.101.64
    ipv6: '2a00:8240:b2b:1::'
  BITTERBAL1:
    asn: 200995
    ipv4: 212.72.236.1
    ipv6: 2001:7bb:b1ba::1
  BOUWHUIS1:
    asn: 202585
    ipv4: 185.244.24.1
    ipv6: 2001:678:d64::1
  BOXED_IT1:
    asn: 50156
    ipv4: 195.200.224.1
    ipv6: 2001:67c:344::1
  BRENNERCOM01:
    asn: 20811
    ipv4: 37.186.150.34
    ipv6: 2a02:490:f02::5
  BRINK1:
    asn: 215248
    ipv4: 103.149.168.204
    ipv6: 2a14:38c0:104:167:19::204
  BUSINESSCONNECT1:
    asn: 15693
    ipv4: 195.191.121.248
    ipv6: 2a01:8800:0:1::1
  BYTEPARK1:
    asn: 45009
    ipv4: 45.150.40.2
    ipv6: '2a0f:9200:0:800:2::'
  CELYA01:
    asn: 203596
    ipv4: 185.122.100.33
    ipv6: 2a06:a400:1:0:600d:fee1:0:1
  CENTAURINET_AMS:
    asn: 46307
    ipv6: 2602:fb3c:11:1::1
  CHAOSDARMSTADT1:
    asn: 6766
    ipv4: 82.195.73.62
    ipv6: 2001:67c:2ed8::1
  CHRISROGERS_PHL:
    asn: 19529
    ipv4: 207.2.124.0
    ipv6: '2602:fd10:10::'
  CHRISROGERS_SJC:
    asn: 19529
    ipv4: 207.2.125.0
    ipv6: '2602:fd10:20::'
  CLOUDIE1:
    asn: 924
    ipv4: 185.121.168.42
    ipv6: 2a06:1280:ce07::42
  CMHMR1:
    asn: 203528
    ipv6: 2a0e:8f02:21d1:dead::90
  CNTDPLKRK:
    asn: 49102
    ipv4: 93.159.133.98
    ipv6: 2a00:1578:2137::1
  COLOCLUE1:
    asn: 8283
    ipv4: 94.142.247.3
    ipv6: 2a02:898:0:300::3
  CONVERTED:
    asn: 54613
    ipv4: 134.195.76.1
    ipv6: 2602:fd9a:1000:603::1
  DAM64:
    asn: 207910
    ipv4: 45.67.83.250
    ipv6: 2001:678:984:b00b::250
  DCSONE1:
    asn: 37989
    ipv4: 203.123.48.6
    ipv6: 2405:fc00::6
  DEVSTORAGE1:
    asn: 210633
    ipv4: 194.50.19.41
    ipv6: 2a0f:5707:ab80:633::1
  DOMINETLLC:
    asn: 210645
    ipv4: 193.148.248.71
    ipv6: 2a0c:9a40:272c::2
  DQN_AMS1:
    asn: 54148
    ipv4: 193.148.248.227
    ipv6: 2602:fa43:80::1
  DQN_MCI1:
    asn: 54148
    ipv4: 23.150.40.155
    ipv6: 2602:fa43:40::1
  DQN_YYZ1:
    asn: 54148
    ipv4: 207.174.104.55
    ipv6: 2602:fa43:10::1
  DUOCAST1:
    asn: 31477
    ipv4: 89.188.4.1
    ipv6: 2a01:01b0:1::1
  DUOCAST2:
    asn: 31477
    ipv4: 89.188.4.16
    ipv6: 2a01:01b0:1::16
  EBOX1:
    asn: 1403
    ipv4: 198.58.198.252
    ipv6: 2606:6d00:eb0::252
  ERICNET1:
    asn: 206628
    ipv4: 134.195.121.1
    ipv6: 2001:678:d3c::0
  ERITAP1:
    asn: 44854
    ipv4: 93.114.180.0
    ipv6: '2a10:e300:26::'
  ERITAP2:
    asn: 44854
    ipv4: 93.114.180.2
    ipv6: 2a10:e300:26::2
  EUROFIBER-AS29396-1:
    asn: 29396
    ipv4: 90.145.153.56
    ipv6: 2a02:120:0:200::c
  EVINY:
    asn: 30950
    ipv4: 193.28.236.32
    ipv6: 2001:67c:324::32
  EWPRATTEN1:
    asn: 54041
    ipv4: 23.142.232.1
    ipv6: '2602:faf5::'
  FASTJET:
    asn: 142453
    ipv4: 103.90.238.1
    ipv6: 2001:df1:2900:4120:103:90:238:1
  FIBERBY1:
    asn: 42541
    ipv4: 193.104.135.79
    ipv6: 2a03:5440:1::79
  FIBERBY2:
    asn: 42541
    ipv4: 193.104.135.78
    ipv6: 2a03:5440:1::78
  FIEBIG:
    asn: 59645
    ipv4: 195.191.197.21
    ipv6: 2a06:d1c0:dead:1::21
  FLORISVDK1:
    asn: 57225
    ipv6: 2a0a:b400::1
  FORK1:
    asn: 807
    ipv4: 23.147.64.2
    ipv6: 2620:39:6000:ffff::2
  FREIFUNKFFM1:
    asn: 64475
    ipv4: 45.157.8.1
    ipv6: 2a0f:3786:10:1::1
  FREIFUNKFFM2:
    asn: 64475
    ipv4: 45.157.9.1
    ipv6: 2a0f:3786:20:1::1
  FREIFUNKRL1:
    asn: 201701
    ipv4: 185.66.195.1
    ipv6: 2a03:2260::4
  FRYSIX1:
    asn: 56393
    ipv4: 185.1.203.254
    ipv6: 2001:7f8:10f::dc49:254
  FRYSIX2:
    asn: 56393
    ipv4: 185.1.203.253
    ipv6: 2001:7f8:10f::dc49:253
  FUNKFEUER_NDC2:
    asn: 35492
    ipv4: 78.41.115.37
    ipv6: 2a02:60:35:492:1:ffff::2
  FUNKFEUER_VIE1:
    asn: 35492
    ipv4: 78.41.115.36
    ipv6: 2a02:60:35:492:1:ffff::1
  FUSIONED_ATH1:
    asn: 51392
    ipv4: 185.157.208.1
    ipv6: 2001:1548:105::1
  FUSIX1:
    asn: 57866
    ipv4: 37.139.139.0
    ipv6: 2a00:a7c0:e20a::0
  FUSIX2:
    asn: 57866
    ipv4: 37.139.139.2
    ipv6: 2a00:a7c0:e20a::2
  GANDI1:
    asn: 29169
    ipv4: 173.246.102.254
    ipv6: 2001:4b98::fe
  GANDI2:
    asn: 29169
    ipv4: 217.70.176.70
    ipv6: 2001:4b98::70
  GITOYEN1:
    asn: 20766
    ipv4: 80.67.168.5
    ipv6: 2001:910::5
  GLOBALCONNECT1:
    asn: 31027
    ipv4: 77.243.32.3
    ipv6: 2a02:188::11:90
  GOCODEIT1:
    asn: 835
    ipv4: 23.159.16.22
    ipv6: 2602:fd50:0:bad::1
  GRIFON1:
    asn: 204092
    ipv4: 89.234.186.6
    ipv6: 2a00:5884::6
  GSHAPIRO:
    asn: 199518
    ipv4: 65.19.141.130
    ipv6: 2001:470:1:b96::2
  HIVANE1:
    asn: 34019
    ipv4: 193.17.192.132
    ipv6: 2001:67c:1740::9
  HOSTWAYDE1:
    asn: 24679
    ipv4: 195.47.229.254
    ipv6: 2a02:790::1
  HYEHOST_AMS1:
    asn: 47272
    ipv4: 89.37.98.120
    ipv6: 2001:678:7ec:120::1
  HYEHOST_FRA1:
    asn: 47272
    ipv4: 154.57.85.83
    ipv6: 2001:67c:d84::1
  HYEHOST_MCI1:
    asn: 47272
    ipv4: 23.172.120.10
    ipv6: 2602:f96d::10
  INFORMATIQ1:
    asn: 215605
    ipv4: 5.181.130.1
    ipv6: 2a0a:6044:8200::1
  INFOWEST1:
    asn: 11071
    ipv4: 209.33.215.64
    ipv6: 2604:2c00::ff:2
  INTERHOST1:
    asn: 61102
    ipv4: 185.37.148.232
  IPFAIL1:
    asn: 62538
    ipv4: 185.101.99.107
    ipv6: 2a04:ad80:2:fe0b::3
  IPFAIL2:
    asn: 62538
    ipv4: 216.218.217.2
    ipv6: 2001:470:1:d27::2
  ISC1280PAO1:
    asn: 1280
    ipv4: 149.20.65.193
    ipv6: 2001:4f8:1b::193
  ITSERVICE1:
    asn: 34681
    ipv4: 193.32.86.1
    ipv6: 2a0e:46c7::1
  IWAY1:
    asn: 8758
    ipv4: 212.25.27.56
    ipv6: 2001:8e0:ffff::56
  KAPSI1:
    asn: 57692
    ipv4: 91.232.154.62
    ipv6: 2001:67c:1be8::62
  KEMMIT1:
    asn: 216084
    ipv4: 88.216.220.1
    ipv6: 2a0e:97c0::1
  KEMMIT2:
    asn: 216084
    ipv4: 45.85.15.1
    ipv6: 2a06:de01:200::1
  KERFUFFLE1:
    asn: 35008
    ipv4: 194.246.109.123
    ipv6: 2602:2d5:4:104::123
  KIT1:
    asn: 34878
    ipv4: 129.13.96.0
    ipv6: 2a00:1398:0:179::1
  KLAB_FRA:
    asn: 13852
    ipv4: 23.190.24.1
    ipv6: 2602:f7ff::1
  KORDIA1:
    asn: 24324
    ipv4: 202.49.135.1
    ipv6: 2404:6c00::96
  KORDIA2:
    asn: 24324
    ipv4: 202.49.135.26
    ipv6: 2404:6c00::93
  KVIKNET_DK01:
    asn: 204151
    ipv4: 185.107.12.53
    ipv6: 2a06:4000:0:4::5
  LIBERTYGLOBAL1:
    asn: 6830
    ipv4: 213.136.1.137
    ipv6: 2001:730:2200::5474:8026
  LONAP1:
    asn: 8330
    ipv4: 5.57.95.90
    ipv6: 2a00:eb20::90
  LONAP2:
    asn: 8330
    ipv4: 5.57.95.91
    ipv6: 2a00:eb20::91
  LONAP3:
    asn: 8330
    ipv4: 5.57.95.92
    ipv6: 2a00:eb20::92
  LSHIY_HKG1:
    asn: 955
    ipv4: 103.203.242.1
    ipv6: 2401:4020:1:1::1
  LUJEnet:
    asn: 212855
    ipv4: 93.157.140.255
    ipv6: 2001:67c:f8c::255
  MASSAR:
    asn: 57777
    ipv4: 185.173.128.2
    ipv6: 2a10:fc42::2
  MASTERDC1:
    asn: 24971
    ipv4: 81.31.40.9
    ipv6: 2a01:430:0:ff::9
  MCIU_PHL:
    asn: 32554
    ipv4: 216.162.82.13
    ipv6: 2607:6b40:2000:ffff:401::2
  MEDIACTIVE_FR:
    asn: 197133
    ipv4: 217.114.205.197
    ipv6: 2a02:1740:0:1979::b14d
  MEDIALINE_FRA1:
    asn: 205614
    ipv4: 185.171.47.1
    ipv6: 2a0d:1f80::1
  MEDIALINE_FRA2:
    asn: 205614
    ipv4: 185.171.47.2
    ipv6: 2a0d:1f80::2
  MEDIALINE_FRA3:
    asn: 205614
    ipv4: 185.171.47.6
    ipv6: 2a0d:1f80::6
  MERLIN1:
    asn: 16796
    ipv4: 216.73.71.129
    ipv6: 2620:b0:0:a::2
  METAPEER:
    asn: 13331
    ipv4: 163.237.247.112
    ipv6: 2001:4978:1000::2319:b
  MIDNET_SPRNTX01:
    asn: 16970
    ipv4: 64.40.23.22
    ipv6: 2602:800:1000:100::16
  MILKYWAN1:
    asn: 2027
    ipv4: 80.67.167.1
    ipv6: 2a0b:cbc0:2::1
  MOJI1:
    asn: 47160
    ipv4: 87.236.35.131
    ipv6: 2a0f:3400:0:2::1
  MSU1:
    asn: 2848
    ipv4: 93.180.0.143
    ipv6: 2a00:f480::14
  MYTHICBEASTS01:
    asn: 44684
    ipv4: 176.126.240.44
    ipv6: 2a00:1098:84::a:1
  NCRYPTED1:
    asn: 34465
    ipv4: 154.51.12.197
    ipv6: 2a12:8fc6:cd00:e03:31:a34:465:1
  NEPTUNE1:
    asn: 21700
    ipv4: 23.157.160.4
    ipv6: 2602:fe2e::4
  NETACTUATE1:
    asn: 36236
    ipv4: 104.225.4.202
    ipv6: 2607:fc50:2000:99::1eb
  NETSHELTERDUS1:
    asn: 41047
    ipv4: 87.237.165.4
    ipv6: 2a0e:a6c0::100:66:1:2
  NETSYST:
    asn: 209097
    ipv4: 5.182.144.3
    ipv6: 2a0e:5c00::3
  NEXTHOP1:
    asn: 49788
    ipv4: 91.218.184.60
    ipv6: 2a02:d140:1::60
  NEXTPERTISE1:
    asn: 41960
    ipv4: 77.73.224.2
    ipv6: 2a02:690::2
  NEYRIAL-R2:
    asn: 203352
    ipv4: 185.131.83.244
    ipv6: 2a06:97c0::244
  NORLYS01:
    asn: 39642
    ipv4: 212.10.212.249
    ipv6: 2a03:7400:2202:2::1
  NTT1:
    asn: 2914
    ipv4: 129.250.1.96
    ipv6: 2001:728:0:1000::f00f
  NYNEX1:
    asn: 62023
    ipv4: 109.236.144.125
    ipv6: 2a00:e60:1100::1:1
  OBENETWORK1:
    asn: 3399
    ipv4: 195.128.255.251
    ipv6: 2a07:5cc0::500:705:2002
  ODERLAND01:
    asn: 44136
    ipv4: 193.180.19.2
    ipv6: 2a02:28f0:101:1::1001
  OPENBSD1:
    asn: 22512
    ipv4: 204.209.252.3
    ipv6: 2620:3d:c000:1230::34
  PAOCLOUD01:
    asn: 133504
    ipv4: 103.230.123.219
    ipv6: 2401:93e0:5:255:2::22
  PARADOXNETWORKS_MCI:
    asn: 52025
    ipv4: 192.209.63.17
    ipv6: '2a05:dfc1:479::'
  PBWCOMM01:
    asn: 16409
    ipv4: 204.9.92.1
    ipv6: 2604:5e40:102::1
  PCCW1:
    asn: 3491
    ipv4: 63.218.242.10
    ipv6: 2400:8800:3e06::10
  PCCW2:
    asn: 3491
    ipv4: 63.218.218.13
    ipv6: 2400:8800:5e08::13
  PCCW3:
    asn: 3491
    ipv4: 63.218.72.11
    ipv6: 2400:8800:7e02::11
  PCCW4:
    asn: 3491
    ipv4: 63.218.164.14
    ipv6: 2400:8800:1e02::14
  PCCW5:
    asn: 3491
    ipv4: 63.223.48.9
    ipv6: 2400:8800:3e0d::6
  PCCW7:
    asn: 3491
    ipv4: 63.218.156.9
    ipv6: 2400:8800:1e04::9
  PFALZKOM-MAN:
    asn: 21473
    ipv4: 212.65.5.201
    ipv6: 2a00:1e80:2::151
  PFALZKOM-MUT:
    asn: 21473
    ipv4: 212.65.5.202
    ipv6: 2a00:1e80:2::152
  PIXELHOSTING1:
    asn: 215085
    ipv4: 83.142.31.1
    ipv6: 2a06:9f41:a100::1
  PNET:
    asn: 200273
    ipv4: 77.237.52.14
    ipv6: 2a01:190:1337::114
  POPNIX1:
    asn: 135063
    ipv4: 103.208.24.2
    ipv6: 2404:3a80:42::1
  QUXLABS1:
    asn: 203038
    ipv4: 185.243.23.254
    ipv6: 2a0d:bbc0:1::1
  RADISHNETWORKS1:
    asn: 399580
    ipv4: 209.209.88.249
    ipv6: 2606:5040::249
  RAOULBROUNS:
    asn: 215296
    ipv4: 103.147.153.15
    ipv6: 2001:67c:e3c::1
  RAPDODGENET:
    asn: 203868
    ipv6: 2a0a:280:b00a:1::1
  ROOTNL:
    asn: 16350
    ipv4: 217.119.226.1
    ipv6: 2a02:1398:800:5000::1:1
  ROUTINGCAFE1:
    asn: 207487
    ipv4: 94.26.24.1
    ipv6: 2a14:14c0::1
  RVDM:
    asn: 57048
    ipv6: 2a0e:f7c0::1
  RZHAS1:
    asn: 44973
    ipv4: 93.88.224.73
    ipv6: 2a02:218:1:1::73
  RZHAS2:
    asn: 44973
    ipv4: 93.88.224.74
    ipv6: 2a02:218:1:1::74
  SAMIP1:
    asn: 213021
    ipv6: 2001:67c:1104::1
  SBTAP1:
    asn: 59715
    ipv4: 185.5.200.255
    ipv6: 2a02:cdc5:9715:0:185:5:200:255
  SCN-RC01:
    asn: 53343
    ipv4: 23.131.12.68
    ipv6: 2602:f765:880::1:0:c0c0
  SECUREBIT_FRE01:
    asn: 58057
    ipv4: 185.102.84.251
    ipv6: 2a09:4c0:f00:b966::54fb
  SECUREBIT_ZUR01:
    asn: 58057
    ipv4: 193.33.94.251
    ipv6: 2a09:4c0:100:c121::5efb
  SECUREBIT_ZUR02:
    asn: 58057
    ipv4: 193.33.94.252
    ipv6: 2a09:4c0:100:c121::5efc
  SENTIAAMS5:
    asn: 8315
    ipv4: 185.74.76.8
    ipv6: 2a02:2858:500:4::1
  SENTIAAMS6:
    asn: 8315
    ipv4: 185.74.76.9
    ipv6: 2a02:2858:500:5::1
  SERNET1:
    asn: 41955
    ipv4: 185.199.216.3
    ipv6: 2a0a:a3c0::2:1
  SERVERION1:
    asn: 213035
    ipv4: 185.28.37.200
    ipv6: '2a10:1440:0:a::'
  SERVERION2:
    asn: 213035
    ipv4: 185.28.37.201
    ipv6: 2a10:1440:0:a::1
  SERVEU:
    asn: 13058
    ipv4: 192.108.73.66
    ipv6: 2a0c:7286:2736::66
  SIACOM_GE:
    asn: 198150
    ipv4: 46.8.37.63
    ipv6: 2a13:9cc3:0::63
  SIDN1:
    asn: 1140
    ipv4: 193.176.144.92
    ipv6: 2a00:d78::193:176:144:92
  SKHRON_WAW01:
    asn: 215467
    ipv4: 88.218.206.2
    ipv6: 2a09:b280:fe00::2
  SPARKED_MFL_01:
    asn: 397032
    ipv4: 23.230.3.1
    ipv6: 2602:fa87:1::1
  SPARKED_PAR_01:
    asn: 397032
    ipv4: 45.43.163.1
    ipv6: 2602:fa87:6:100::1
  STOCADE_AMS_01:
    asn: 214809
    ipv6: 2a0a:6044:b304::1
  SYSLEVEL:
    asn: 57797
    ipv6: 2a12:8ac1:a0::60
  SYSTEM36_EWR01:
    asn: 59678
    ipv4: 23.148.232.1
    ipv6: 2602:fa9b:1::1
  TECHFUTURES_YVR1_RT1:
    asn: 394256
    ipv4: 192.30.89.241
    ipv6: 2606:9580::1
  TECHFUTURES_YVR1_RT2:
    asn: 394256
    ipv4: 192.30.89.242
    ipv6: 2606:9580::2
  TELSENSE:
    asn: 329035
    ipv4: 102.216.24.5
    ipv6: 2c0f:4c80:0:1::5
  TETANEUTRAL1:
    asn: 197422
    ipv4: 91.224.149.152
    ipv6: 2a03:7220:8081:9800::1
  TFSKOK1:
    asn: 49420
    ipv4: 46.28.243.194
    ipv6: 2a02:2978:c:c::12
  TING:
    asn: 32133
    ipv4: 64.98.10.8
    ipv6: 2606:8e80:64::8
  TMW_AMS:
    asn: 215828
    ipv4: 77.90.25.254
    ipv6: 2a0e:b107:27f9::1
  TMW_FFM:
    asn: 215828
    ipv4: 23.133.205.0
    ipv6: 2a0e:b107:27f5::1
  TRITAN:
    asn: 393577
    ipv4: 23.142.248.1
    ipv6: 2602:291::1
  TUXISAMS1:
    asn: 197731
    ipv4: 185.119.29.17
    ipv6: 2a03:7900:0:5::1
  TV2DANMARK1:
    asn: 56496
    ipv4: 91.224.211.117
  UNILOGIC1:
    asn: 28788
    ipv4: 62.133.192.15
    ipv6: 2001:4128:6135:210:250:56ff:feb6:3e
  VMCITY_RU:
    asn: 51093
    ipv4: 212.48.225.134
    ipv6: 2a06:300:10::133
  VOCUS1:
    asn: 4826
    ipv4: 114.31.199.17
    ipv6: 2402:7800:100::17
  VOCUS2:
    asn: 4826
    ipv4: 114.31.199.18
    ipv6: 2402:7800:100::18
  WAVEX_MBA1_PE1:
    asn: 328977
    ipv4: 102.217.156.8
    ipv6: '2c0f:6300:0:ff6::'
  WAVEX_NBO1_PE1:
    asn: 328977
    ipv4: 102.217.156.3
    ipv6: '2c0f:6300:eadc::3'
  WAVEX_NBO1_PE2:
    asn: 328977
    ipv4: 102.217.156.2
    ipv6: '2c0f:6300:eadc::2'
  WD61:
    asn: 20495
    ipv4: 217.148.191.1
    ipv6: 2001:15c8:1::1
  XINDI1:
    asn: 48112
    ipv4: 185.173.16.135
    ipv6: 2a0b:2f00:0:234::135
  XODO:
    asn: 44570
    ipv4: 103.208.86.228
    ipv6: 2a06:1280:bee1:2::ee12:603
  XTOM1:
    asn: 3214
    ipv4: 185.255.55.19
    ipv6: 2a0c:59c0::19
  XYPHENIT_CE_AMS:
    asn: 211588
    ipv4: 45.83.205.255
    ipv6: 2a07:e345::255
  YOURORG_ORD1:
    asn: 19255
    ipv4: 163.237.247.99
    ipv6: 2001:4978:1000::2319:99

readonly_peers:
  SERNET2:
    asn: 41955
    ipv4: 185.199.217.227
    ipv6: 2a0a:a3c0:0:d2ca::217:227
  XINDI_RC0:
    asn: 57984
    ipv4: 91.207.120.39
    ipv6: 2a0b:2f07:abcd:234::39
  BASED_RC0THTP:
    asn: 21991
    ipv4: 198.8.59.40
    ipv6: '2a0f:85c1:31:2c::'
