lg_peers:
  ADISTA1:
    asn: 16347
    ipv4: 212.51.161.36
    ipv6: 2a01:728::6
  AFILIAS_IAD1:
    asn: 393246
    ipv4: 199.115.158.251
    ipv6: 2001:500:A6::251
  AFILIAS_MIA2:
    asn: 33280
    ipv4: 65.22.12.251
    ipv6: 2A01:8840:C::251
  AFILIAS_TKY1:
    asn: 13901
    ipv4: 199.19.52.251
    ipv6: 2001:500:a::251
  AFILIAS_TKY2:
    asn: 13901
    ipv4: 199.19.52.252
    ipv6: 2001:500:a::252
  ALARIG1:
    asn: 208627
    ipv4: 45.91.126.248
    ipv6: 2a0e:f42:ffff::
  ALARIG2:
    asn: 208627
    ipv4: 45.91.126.249
    ipv6: 2a0e:f42:ffff::2
  ALTIBOX1:
    asn: 29695
    ipv4: 79.160.115.253
    ipv6: 2a01:798:0:1::262
  AQUILENET1:
    asn: 198985
    ipv4: 185.233.100.246
    ipv6: 2a0c:e300:1::246
  AQUILENET2:
    asn: 198985
    ipv4: 185.233.100.247
    ipv6: 2a0c:e300:1::247
  ARNFAI1:
    asn: 60630
    ipv4: 89.234.141.131
    ipv6: 2a00:5881:8100::131
  BELWUE1:
    asn: 553
    ipv4: 129.143.4.244
    ipv6: 2001:7c0:0:1000::1
  BIT1:
    asn: 12859
    ipv4: 213.136.1.132
    ipv6: 2001:7b8:0:fffe::2
  BLIX1:
    asn: 50304
    ipv4: 31.169.49.228
    ipv6: 2a02:20c8:1f::12
  BOXED_IT1:
    asn: 50156
    ipv4: 195.200.224.1
    ipv6: 2001:67c:344::1
  BRENNERCOM01:
    asn: 20811
    ipv4: 95.171.40.4
    ipv6: 2A02:490:F02::1
  CDW1:
    asn: 3599
    ipv4: 64.73.0.252
    ipv6: 2607:FEE0:0:FF00::A2
  CELYA01:
    asn: 203596
    ipv4: 185.122.100.33
    ipv6: 2a06:a400:1:0:600d:fee1:0:1
  CHAOSDARMSTADT1:
    asn: 6766
    ipv4: 82.195.73.62
    ipv6: 2001:67c:2ed8::1
  CLOUDDK1:
    asn: 203453
    ipv4: 185.134.31.249
    ipv6: 2a06:eac0:42::1
  COLOCLUE1:
    asn: 8283
    ipv4: 94.142.247.3
    ipv6: 2a02:898:0:300::3
  CUSTODIAN:
    asn: 50300
    ipv4: 176.12.110.8
    ipv6: 2A00:1C10:10::8
  CYBERCOM1:
    asn: 51164
    ipv4: 178.217.128.1
    ipv6: 2001:67c:224::1
  CYBERCOM2:
    asn: 51164
    ipv4: 178.217.128.2
    ipv6: 2001:67c:224::2
  DCSONE1:
    asn: 37989
    ipv4: 203.123.48.6
    ipv6: 2405:fc00::6
  DHIRAAGU01:
    asn: 7642
    ipv4: 202.1.192.176
    ipv6: 2406:e400:0:b::b3
  DIGITALOCEAN1:
    asn: 14061
    ipv4: 198.199.99.2
    ipv6: 2604:a880:1::2
  DNA1:
    asn: 16086
    ipv4: 217.78.199.200
    ipv6: 2001:14b8:1080:0200::1001
  DRAGON1:
    asn: 15614
    ipv4: 213.168.176.62
    ipv6: 2a02:13b8:1:d::1
  DUOCAST1:
    asn: 31477
    ipv4: 89.188.4.1
    ipv6: 2A01:01B0:1::1
  DUOCAST2:
    asn: 31477
    ipv4: 89.188.4.2
    ipv6: 2A01:01B0:1::2
  EDSITECH:
    asn: 202194
    ipv4: 185.50.188.1
    ipv6: 2a04:c000::1
  EDUTEL1:
    asn: 39309
    ipv4: 88.159.0.21
    ipv6: 2a01:670::21
  FIBERBY1:
    asn: 42541
    ipv4: 193.104.135.79
    ipv6: 2a03:5440:1::79
  FIBERBY2:
    asn: 42541
    ipv4: 193.104.135.78
    ipv6: 2a03:5440:1::78
  FREIFUNKRL1:
    asn: 201701
    ipv4: 185.66.195.1
    ipv6: 2a03:2260::4
  FUSIX1:
    asn: 57866
    ipv4: 37.139.139.0
    ipv6: 2a00:a7c0:e20a::0
  GANDI1:
    asn: 29169
    ipv4: 173.246.102.254
    ipv6: 2001:4b98::fe
  GANDI2:
    asn: 29169
    ipv4: 217.70.176.70
    ipv6: 2001:4b98::70
  GO6LAB1:
    asn: 198644
    ipv4: 91.239.96.218
    ipv6: 2001:67C:27E4:1::1036
  GRIFON1:
    asn: 204092
    ipv4: 89.234.186.6
    ipv6: 2a00:5884::6
  HEXTET1:
    asn: 395089
    ipv4: 192.160.102.137
    ipv6: 2620:132:3003:300::137
  HIBERNIA02:
    asn: 5580
    ipv4: 80.94.64.124
    ipv6: 2a02:d28:5580::63
  HIVANE1:
    asn: 34019
    ipv4: 193.17.192.132
    ipv6: 2001:67c:1740::9
  HOSTWAY1:
    asn: 14280
    ipv4: 64.40.105.22
    ipv6: 2606:6a00::e
  HOSTWAYDE1:
    asn: 24679
    ipv4: 195.47.229.254
    ipv6: 2a02:790::1
  ICCN1:
    asn: 40387
    ipv4: 72.36.126.1
    ipv6: 2620:0:e10:1::1
  IMMENSE01:
    asn: 7954
    ipv4: 104.254.52.0
    ipv6: 2605:E380::0
  INFOWEST1:
    asn: 11071
    ipv4: 209.33.215.64
    ipv6: 2604:2c00::ff:2
  INTERHOST1:
    asn: 61102
    ipv4: 185.37.148.232
  IPMAX1:
    asn: 25091
    ipv4: 46.20.255.5
    ipv6: 2A02:2528:101:3::1
  IPMAX2:
    asn: 25091
    ipv4: 46.20.255.6
    ipv6: 2A02:2528:201:3::1
  ISPSERVICES1:
    asn: 24875
    ipv4: 212.79.241.2
    ipv6: 2001:968:10::2
  ISPSERVICES2:
    asn: 24875
    ipv4: 212.79.241.4
    ipv6: 2001:968:10::4
  IWAY1:
    asn: 8758
    ipv4: 212.25.27.39
    ipv6: 2001:8e0:0:ffff::2
  JPBE1:
    asn: 206479
    ipv4: 185.120.22.16
    ipv6: '2001:67c:16c8:18d1::1'
  KANREN1:
    asn: 2495
    ipv4: 164.113.193.221
    ipv6: 2001:49d0:2000:1036::1
  KUDELSKI1:
    asn: 200584
    ipv4: 85.184.255.154
  MILKYWAN1:
    asn: 57199
    ipv4: 80.67.167.4
    ipv6: 2a0b:cbc0:2::8
  MNETWORKS1:
    asn: 198611
    ipv4: 87.245.248.237
    ipv6: 2001:978:2:c1::8:2
  MNETWORKS2:
    asn: 198611
    ipv4: 87.245.245.107
  MSU1:
    asn: 2848
    ipv4: 93.180.0.143
    ipv6: 2a00:f480::14
  NEPTUNE1:
    asn: 397143
    ipv4: 23.157.160.1
    ipv6: 2602:fe2e::1
  NETSIGN1:
    asn: 31078
    ipv4: 217.115.0.27
    ipv6: 2a00:1328:e00e::27
  NIANET1:
    asn: 31027
    ipv4: 77.233.230.4
  NODESDIRECT1:
    asn: 19531
    ipv4: 208.84.135.58
    ipv6: 2604:4600::d054:873a
  NONATTACHED1:
    asn: 57821
    ipv6: 2001:67c:26f4::1
  NYNEX1:
    asn: 62023
    ipv4: 109.236.144.125
    ipv6: 2a00:e60:1100::1:1
  OBENETWORK1:
    asn: 197595
    ipv4: 46.227.64.248
    ipv6: 2a03:8600:8600:1::8
  PBWCOMM01:
    asn: 16409
    ipv4: 38.103.8.1
    ipv6: 2001:550:102::1
  QCOM:
    asn: 41497
    ipv4: 212.183.160.2
    ipv6: 2001:4bb0:100::2
  QUADRANET3:
    asn: 8100
    ipv4: 96.44.143.30
    ipv6: 2607:fcd0:da80::11
  QUADRANET4:
    asn: 8100
    ipv4: 173.44.32.245
    ipv6: 2607:ff48:aa81:400::1
  SBTAP1:
    asn: 59715
    ipv4: 185.5.200.255
    ipv6: 2A02:CDC5:9715:0:185:5:200:255
  SIDN1:
    asn: 1140
    ipv4: 193.176.144.93
    ipv6: 2a00:d78::193:176:144:93
  SVWH1:
    asn: 394738
    ipv4: 162.213.3.255
    ipv6: 2606:c680::ffff
  SVWH2:
    asn: 394738
    ipv4: 162.213.3.252
    ipv6: 2606:c680::fffc
  TETANEUTRAL1:
    asn: 197422
    ipv4: 91.224.149.152
    ipv6: 2a03:7220:8081:9800::1
  TFSKOK1:
    asn: 49420
    ipv4: 46.28.243.194
    ipv6: 2a02:2978:c:c::12
  TWOCONNECT1:
    asn: 35236
    ipv4: 109.205.72.24
    ipv6: 2a00:1238:0:22::24
  VMHAUS1:
    asn: 136620
    ipv4: 185.214.69.1
    ipv6: 2a06:82c2::1
  VOCUS1:
    asn: 4826
    ipv4: 114.31.199.1
    ipv6: 2402:7800:100::1
  VOCUS2:
    asn: 4826
    ipv4: 114.31.199.22
    ipv6: 2402:7800:100::22
  WIREHIVE1:
    asn: 56730
    ipv4: 134.0.17.140
    ipv6: 2a03:b980:102::c1
  XINDI1:
    asn: 48112
    ipv4: 185.173.16.135
    ipv6: 2a0b:2f00:0:234::135
  XING1:
    asn: 50343
    ipv4: 185.169.112.240
    ipv6: 2a01:8780:1::1
  XING2:
    asn: 50343
    ipv4: 185.169.113.240
    ipv6: 2a01:8781:1::1
  YOURORG1:
    asn: 19255
    ipv4: 216.14.98.5
    ipv6: 2001:4978:1:10::ffff
  ZEROFAIL1:
    asn: 40191
    ipv4: 216.221.157.162
    ipv6: 2001:668:0:3::8000:1712
  LIBERTYGLOBAL1:
    asn: 6830
    ipv4: 213.46.182.33
    ipv6: 2001:730:2206:14::d52e:b121
  KIT1:
    asn: 34878
    ipv4: 129.13.96.0
    ipv6: 2a00:1398:0:179::1
  BELLMTS1:
    asn: 394255
    ipv4: 216.55.208.166
    ipv6: 2606:5c80:2:8::1
  NTT1:
    asn: 2914
    ipv4: 129.250.1.96
    ipv6: 2001:728:0:1000::f00f
  FREIFUNKFFM1:
    asn: 64475
    ipv4: 185.206.209.0
    ipv6: 2a06:8187:fb10::1
  UNILOGIC1:
    asn: 28788
    ipv4: 62.133.192.15
    ipv6: 2001:4128:6135:210:250:56ff:feb6:3e 
  NESSUS1:
    asn: 47692
    ipv4: 77.244.255.5
    ipv6: 2a02:1b8::5
  SERNET1:
    asn: 41955
    ipv4: 185.199.216.3
    ipv6: 2a0a:a3c0::2:1
  IPB1:
    asn: 20647
    ipv4: 91.102.8.233
    ipv6: 2a02:f28::233
  PCCW1:
    asn: 3491
    ipv4: 63.218.242.9
    ipv6: 2400:8800:3e06::9
  PCCW2:
    asn: 3491
    ipv4: 63.218.218.10
    ipv6: 2400:8800:5e08::10
  PCCW3:
    asn: 3491
    ipv4: 63.218.72.11
    ipv6: 2400:8800:7e02::11
  PCCW4:
    asn: 3491
    ipv4: 63.218.164.14
    ipv6: 2400:8800:1e02::14
  EBOX1:
    asn: 1403
    ipv4: 198.58.198.255
    ipv6: 2606:6d00:eb0::255
  NETSHELTER1:
    asn: 49697
    ipv4: 89.46.125.1
    ipv6: 2a06:8187:fe01::1
  NEXRIL1:
    asn: 13830
    ipv4: 192.34.100.0
    ipv6: 2001:506:30::0
  NETACTUATE1:
    asn: 36236
    ipv4: 208.111.38.185
    ipv6: 2607:f740:0:7::f79
  LEVEL66NETWORK1:
    asn: 209844
    ipv4: 141.98.136.1
    ipv6: 2a09:11c0::1
  G8NET1:
    asn: 28329
    ipv4: 186.226.80.255
    ipv6: 2804:39c:1fff:ffff:ffff:ffff:ffff:ffff
  G8NET2:
    asn: 28329
    ipv4: 186.226.80.251
    ipv6: 2804:39c:1fff:ffff:ffff:ffff:ffff:fffe
  XTOM1:
    asn: 3214
    ipv4: 185.255.55.19
    ipv6: 2a0c:59c0::19
  OVERTHEWIRE1:
    asn: 9268
    ipv4: 203.62.187.178
    ipv6: 2402:C00::178
  ATOM861:
    asn: 8455
    ipv4: 95.142.96.25
    ipv6: 2a00:1188::10
  ATOM862:
    asn: 8455
    ipv4: 95.142.96.26
    ipv6: 2a00:1188::11

readonly_peers:
  ISOLARIO1:
    asn: 2598
    ipv4: 192.65.131.25
    ipv6: 2001:67c:1b08:a:192:65:131:25
  SERNET2:
    asn: 41955
    ipv4: 185.199.217.227
    ipv6: 2a0a:a3c0:0:d2ca::217:227
  BGPDOTTOOLS:
    asn: 4294967290
    ipv4: 185.230.223.92
    ipv6: 2a0c:2f07:9459:592::2
  TWENTYC:
    asn: 35848
    ipv4: 204.130.133.163
    ipv6: 2607:fae0:f202:44c::163
