---
software:
  all:
    - apache2-utils
    - bash-completion
    - bc
    - bind9-host
    - bison
    - build-essential
    - bzr
    - cmake
    - curl
    - cvs
    - datamash
    - dnsdiag
    - dnsutils
    - dnsviz
    - dsniff
    - flex
    - fpdns
    - fping
    - git
    - gnupg
    - gnutls-bin
    - gping
    - graphviz
    - hash-slinger
    - hping3
    - htop
    - httping
    - iotop
    - ipcalc
    - iperf
    - iperf3
    - iputils-ping
    - iputils-tracepath
    - jq
    - jsonlint
    - landscape-common
    - language-pack-en-base
    - ldnsutils
    - lft
    - lftp
    - libcache-cache-perl
    - libldns-dev
    - libsqlite3-dev
    - libxml2-dev
    - lsof
    - ltrace
    - lynx
    - man-db
    - markdown
    - members
    - mercurial
    - moreutils
    - mtr-tiny
    - nano
    - ndisc6
    - net-tools
    - netcat-openbsd
    - netsed
    - ngrep
    - nmap
    - parallel
    - pastebinit
    - psmisc
    - pv
    - python3
    - python3-demjson
    - python3-dev
    - python3-dnspython
    - python3-flask
    - python3-mysqldb
    - python3-pip
    - python3-pycountry
    - python3-requests
    - python3-scapy
    - python3-simplejson
    - python3-unidecode
    - python3-virtualenv
    - python3-venv
    - rsync
    - ruby
    - ruby-dev
    - ruby-json
    - screen
    - sipcalc
    - snmp
    - socat
    - strace
    - swaks
    - sysstat
    - tcpdump
    - tcptraceroute
    - telnet
    - tmux
    - traceroute
    - trippy
    - tshark
    - ucspi-tcp
    - unattended-upgrades
    - update-manager-core
    - update-notifier-common
    - vim
    - virt-what
    - w3m
    - wget
    - whois
